name: Bug report
description: Report something that is broken or incorrect
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        **Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)
        detailing how to provide the necessary information for us to reproduce your bug. In brief:
          * Please provide exact steps how to reproduce the bug in a clean Python environment.
          * In case it's not clear what's causing this bug, please provide the data or the data generation procedure.
          * Replicate problems on public or simulated data (`tcri.datasets`), or share data subsets when full sharing isn't possible.

  - type: textarea
    id: report
    attributes:
      label: Report
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: |
        Which version of packages.

        Please install `session-info2`, run the following command in a notebook,
        click the “Copy as Markdown” button, then paste the results into the text box below.

        ```python
        In[1]: import session_info2; session_info2.session_info(dependencies=True)
        ```

        Alternatively, run this in a console:

        ```python
        >>> import session_info2; print(session_info2.session_info(dependencies=True)._repr_mimebundle_()["text/markdown"])
        ```
      render: python
      placeholder: |
        tcri	0.12.0
        scvi-tools	1.5.0.post1
        pyro-ppl	1.9.1
        torch	2.13.0
        anndata	0.13.2
        scanpy	1.12.3
        ----	----
        Python	3.14.7
        OS	macOS-26.6.2-arm64-arm-64bit-Mach-O
